steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/maplepath-api:$COMMIT_SHA', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/maplepath-api:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'maplepath-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/maplepath-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL_PROD=$DATABASE_URL_PROD,SECRET_KEY=$SECRET_KEY,FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json'
      - '--set-cloudsql-instances'
      - '$PROJECT_ID:us-central1:maplepath-db'
      - '--port'
      - '8080'

timeout: 900s